### ISSUE TITLE
Automatically use lld for cross compilation

### ISSUE THREAD

**Issue by kryptan** [rust-lang/rustup#1564]
I was cross-compiling from windows to linux-musl and figured out that I don't actually need to install any separate linker. I can just point cargo to the lld that rustup has installed anyway:

```toml
[target.x86_64-unknown-linux-musl]
linker = "C:/Users/<username>/.rustup/toolchains/nightly-x86_64-pc-windows-msvc/lib/rustlib/x86_64-pc-windows-msvc/bin/rust-lld.exe"
```

After adding this to my `.cargo/config` it just works (of course as long as I don't depend on any C code).

It would be nice if I didn't need to configure this manually. Not sure if this is cargo or rustup issue.
