### ISSUE TITLE
Compilation fails with default-features = false

### ISSUE THREAD

**Issue by cmyr** [rust-lang/rustup#1789]
**Problem**

The rustup crate fails to build if either of the `curl-backend` or `reqwest-backend` features are not selected.

**Steps**
1. Create a new cargo project, and include in the manifest:

```toml
[dependencies.rustup]
version = "1.17"
git = "https://github.com/rust-lang/rustup.rs.git"
default-features = false
```

2. Run `cargo check` or `cargo build`

**Possible Solution(s)**
Update the two fallback modules in [download/src/lib.rs](https://github.com/rust-lang/rustup.rs/blob/master/download/src/lib.rs#L368) to compile under the 2018 edition.

**Notes**

I appreciate that this crate is not intended for public consumption etc. 😁 I'm playing around with building a rust playground, and wanted to use rustup internals to query available toolchains etc. If this is a Bad Idea please let me know!

I will prepare a PR, since I assume this is a simple oversight, and I'm in the code.

rustup version: 373448b032aec0054
