### ISSUE TITLE
Support additional toolchain channels in rust-toolchain.toml? 

### ISSUE THREAD

**Issue by jmjoy** [rust-lang/rustup#3355]
### Problem you are trying to solve

Somethings we have to use multi toolchains in a project, usually stable and nightly, like:

```shell
cargo build --release
cargo +nightly fmt --all
cargo +nightly rustdoc 
```

Because we prefer to stable toolchain, but there are some useful features in nightly for `format` and `rustdoc`.

But, we can only use latest nightly version with `+nightly`, or hard code the nightly version `+nightly-2023-01-01`.

### Solution you'd like

Add the new field in `rust-toolchain.toml`, such as:

```toml
[toolchain.custom.foo]
channel = "nightly-2020-07-10"
components = [ "rustfmt", "rustc-dev" ]
targets = [ "wasm32-unknown-unknown", "thumbv2-none-eabi" ]
profile = "minimal"
```

and then, we can use this custom toolchain by:

```shell
cargo +foo fmt --all
```

### Notes

Maybe there's a better way.
