### ISSUE TITLE
Checksum files for manual installation

### ISSUE THREAD

**Issue by darthbanana13** [rust-lang/rustup#3693]
### Problem

If installation is attempted with the manual method, documented here: https://rust-lang.github.io/rustup/installation/other.html, a download tool with an automatic checksum verifier fails because the path for downloaded file has a path prepended.

### Steps

For example with ansible:

Create a local _hosts.yaml_ file:
```
dev:
  localhost:
    ansible_connection: local
```

Create a _playbook.yaml_:
```
- hosts: dev
  roles:
    - rustup
```

Create _role_ directory.
In it use command: `ansible-glalaxy init rustup`
To create an empty role.

Edit main.yaml in tasks to:
```
---
- name: Download rustup-init
  ansible.builtin.get_url:
    url: "https://static.rust-lang.org/rustup/dist/armv7-unknown-linux-gnueabihf/rustup-init"
    dest: /tmp/rustup-init
    checksum: "sha256:https://static.rust-lang.org/rustup/dist/armv7-unknown-linux-gnueabihf/rustup-init.sha256"
    mode: "0555"
```

Run the playbook from the plabook file location:
`ansible-playbook -i hosts.yaml bootstrap.pb.yaml`

See error:
`FAILED! => {"changed": false, "msg": "Unable to find a checksum for file 'rustup-init' in 'https://static.rust-lang.org/rustup/dist/armv7-unknown-linux-gnueabihf/rustup-init.sha256'"}`

### Possible Solution(s)

Use only the executable name in the sha256 file. Instead of:
`f21c44b01678c645d8fbba1e55e4180a01ac5af2d38bcbd14aa665e0d96ed69a *target/armv7-unknown-linux-gnueabihf/release/rustup-init`
use:
`f21c44b01678c645d8fbba1e55e4180a01ac5af2d38bcbd14aa665e0d96ed69a ./rustup-init`
or
`f21c44b01678c645d8fbba1e55e4180a01ac5af2d38bcbd14aa665e0d96ed69a rustup-init`

Examples of other projects doing it with only the executables in the sha file:
[Neovim](https://github.com/neovim/neovim/releases/tag/v0.9.5)
[Mise](https://github.com/jdx/mise/releases/tag/v2024.3.1)

### Rustup version

```console
Rustup was not installed
```

### Installed toolchains

```console
Rustup was not installed
```
