### ISSUE TITLE
FreeBSD CI failure possibly caused by `rustls-platform-verifier`

### ISSUE THREAD

**Issue by rami3l** [rust-lang/rustup#3908]
@djc Unfortunately, #3903 has seemingly broken our FreeBSD CI:

> error: could not download file from 'https://static.rust-lang.org/rustup/release-stable.toml' to '/tmp/rustup-update68roIr/release-stable.toml': failed to make network request: error sending request for url (https://static.rust-lang.org/rustup/release-stable.toml): client error (Connect): received fatal alert: DecodeError

I have completely no idea why that is the case. Doesn't look like a network problem either: a few minutes ago there was another FreeBSD test and it passed; a few minutes later there was a third FreeBSD test and it failed.

I'm not sure what this `DecodeError` is. Could it be `X.509`-related?

**Comment by rami3l** [comment]
> I guess that would be because of https://github.com/rustls/rustls-native-certs/issues/28. Apparently somehow we were previously pulling in webpki-roots (perhaps in addition rustls-native-certs)?

_Originally posted by @djc in https://github.com/rust-lang/rustup/issues/3903#issuecomment-2188680914_

**Comment by rami3l** [comment]
> I guess that would be because of [rustls/rustls-native-certs#28](https://github.com/rustls/rustls-native-certs/issues/28). Apparently somehow we were previously pulling in webpki-roots (perhaps in addition rustls-native-certs)?

@djc In #3903 `rustls-native-certs` and `webpki-roots` were introduced as dependencies of `rustls-platform-verifier`. The former used to be a dependency of `reqwest` (this is no longer the case), but the latter is completely new.

**Comment by djc** [comment]
Right, that's a pretty limited dependency:

```toml
[target.'cfg(target_arch = "wasm32")'.dependencies]
webpki-roots = "0.26"

# BSD targets require webpki-roots for the real-world verification tests.
[target.'cfg(target_os = "freebsd")'.dev-dependencies]
webpki-roots = "0.26"
```

But my point was, before #3903 we were using `reqwest/rustls-tls-native-roots` which should also have been using rustls-native-certs on FreeBSD -- so I'm confused why this only started to fail now.
