### ISSUE TITLE
Q/A: Temporarly disable auto-updates

### ISSUE THREAD

**Issue by eirnym** [rust-lang/rustup#4168]
When I run `cargo build`, `rustup` runs an automatic update (stable channel). It's nice, but it's not desired for any circumstances (e.g. I'm in a train and try to build a project).

How would I temporarily disable automatic updates of stable/nightly channels.

Contents of my `${RUSTUP_HOME/settings.toml}`:

```toml
default_host_triple = "aarch64-apple-darwin"
default_toolchain = "stable-aarch64-apple-darwin"
profile = "default"
version = "12"
auto-self-update = "check-only"

[overrides]
```

*Additional notes:*

In zshrc I don't call `rustup-init`:

* RUSTUP_HOME is set to a specific folder
* in zshrc I have `alias rustup='CARGO_HOME=$RUSTUP_HOME/.cargo rustup'`
* For `cargo` I use it `cargo` from RUSTUP_HOME by having a symbolic link in my `~/bin/local` folder
* while cargo installs third-party apps into `.cargo/bin` folder.
