### ISSUE TITLE
Provide a warning when using custom toolchains with extra components

### ISSUE THREAD

**Issue by rami3l** [rust-lang/rustup#4252]
#4250 currently does not provide any custom toolchain validity check when provided with extra components, such as in the configuration below:

```toml
[toolchain]
channel = "ms-1.84.1"
targets = [
    "aarch64-pc-windows-msvc",
    "x86_64-pc-windows-msvc",
]
```

> I think it will probably be worthwhile to add a warning clarifying that we are not doing any checks, as demonstrated in the new test.
_https://github.com/rust-lang/rustup/issues/4250#issuecomment-2722983959_
