### ISSUE TITLE
rustup update nightly sometimes doesn't see the most recent tarball

### ISSUE THREAD

**Issue by nox** [rust-lang/rustup#833]
Today, `rustup update nightly` gives the same version as `nightly-2016-11-21` even though `nightly-2016-11-22` exists.

**Comment by TimNN** [comment]
This seems like a caching Problem:

Using Chrome to download, https://static.rust-lang.org/dist/channel-rust-nightly.toml contains sections like

```toml
[pkg.rust.target.x86_64-apple-darwin]
available = true
url = "https://static.rust-lang.org/dist/2016-11-22/rust-nightly-x86_64-apple-darwin.tar.gz"
hash = "e969929b629d5519525be3c43e858d64c8696b35d8f899a6af89a93897d327e2"
```

Whereas using `curl` gives

```toml
[pkg.rust.target.x86_64-apple-darwin]
available = true
url = "https://static.rust-lang.org/dist/2016-11-21/rust-nightly-x86_64-apple-darwin.tar.gz"
hash = "1ef354dabd1747601ae0343e345186d6e1cd23f6d7376ad9b464b898aba861a7"
```

Adding `-H 'accept-encoding: gzip'  --compressed` to the `curl` command produces the correct nightly.
